services:
  car-price-a2:
    # Replace YOUR_DOCKERHUB_USERNAME and STUDENT_ID before server deployment.
    image: YOUR_DOCKERHUB_USERNAME/car-price-a2:latest
    platform: linux/amd64
    environment:
      - PORT=8501
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.services.car-price-STUDENT_ID.loadbalancer.server.port=8501
      - traefik.http.routers.car-price-STUDENT_ID.rule=Host(`STUDENT_ID.ml.brain.cs.ait.ac.th`)
      - traefik.http.routers.car-price-STUDENT_ID.tls=true
      - traefik.http.routers.car-price-STUDENT_ID.tls.certresolver=production
      - traefik.http.routers.car-price-STUDENT_ID.entrypoints=websecure
    networks:
      - default
      - traefik_default

networks:
  default:
  traefik_default:
    external: true
